### ISSUE TITLE
require self.item_type.underscore Crash

### ISSUE THREAD

**Issue by imton** [liveeditor/draftsman#25]
Using  https://github.com/RubyMoney/money-rails

This line make it crash when reify is called.

````ruby
require self.item_type.underscore
````

https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb#L250
````
raise ArgumentError, "#{self} already has a monetized attribute called '#{name}'"
````

**Comment by chrisdpeters** [comment]
@imton I tried installing `money-rails` and replicating the problem, but everything seemed fine while `reify`ing both `create` and `update` drafts.

Can you provide more context for how you're receiving this error?

I'll be glad to re-open this issue if you can provide more details, or better yet, a simple repo with an app that isolates the problem.
