### ISSUE TITLE
Uh oh, ActiveSupport::DeprecationException error when running generated migrations

### ISSUE THREAD

**Issue by defbyte** [liveeditor/draftsman#39]
:palm_tree: Aloha! :palm_tree:

thanks very much for this gem! I'd been working on a very lo-fi version of this functionality, then said to heck with it and decided to check out your gem. I work on a lot of projects where publishing workflows are A Thing :tm: 

So, I started to fire things up, got this error, and wanted to pass on a quick fix with PR #38 

I hope to contribute more in the future, thanks again.

**Comment by chrisdpeters** [comment]
Thank you, @defbyte! My goal is to get 0.4.0 out the door within a couple weeks, and this will certainly in there.
