### ISSUE TITLE
irb: warn: can't alias context from irb_context.

### ISSUE THREAD

**Issue by panaak** [liveeditor/draftsman#49]
when i load rails console with the latest rspec-rails (3.5.2) together with draftsman i get this warning.

```
Loading development environment (Rails 4.2.7.1)
irb: warn: can't alias context from irb_context.
2.2.5 :001 >
```

**Comment by chrisdpeters** [comment]
@panaak Can you try master and let me know if it's still an issue? If so, feel free to reopen this issue!

**Comment by panaak** [comment]
ok, seems like the master (0.5.1) does not cause this issue anymore.
