### ISSUE TITLE
Is there a way to not mark as trashed on relationships when calling draft_destruction?

### ISSUE THREAD

**Issue by NullVoxPopuli** [liveeditor/draftsman#60]
My situation is that I have a tree structure, and when I trash one node, I want to stitch that node's children to the node's parent node.

Currently, when I call `draft_destruction`, all of the children nodes are also trashed.

**Comment by chrisdpeters** [comment]
@NullVoxPopuli Can you explain a scenario where it makes sense to do this? If a child depends on a parent for its existence, why wouldn't we trash it too?

You may already be aware of this, but I will note that Draftsman will only trash the children if you have `dependent: :destroy` set on the association. (See [model.rb#L294](https://github.com/liveeditor/draftsman/blob/master/lib/draftsman/model.rb#L294).)

Of course, I am open to discussion, and a concrete example may help me better understand.

**Comment by chrisdpeters** [comment]
Ahh, you did have an example in your post. I am guilty of just reading the headlines, I guess!

Can you create a `before_draft_destruction` callback that reassigns the children before the parent record is trashed?

**Comment by NullVoxPopuli** [comment]
yeah -- for now I removed `dependent: :destroy`

since I have migrated my draftable models to be a tree, I don't think I want `dependent: :destroy` ever, actually (rather a delete node and stitch the deleted node's descendants to the deleted node's parent).

So... I'll re-open this later if a use case comes up.

**Comment by NullVoxPopuli** [comment]
@chrisdpeters that's actually good idea if I want dependent destroy again. huh.

**Comment by chrisdpeters** [comment]
@NullVoxPopuli Fair enough. Glad we could exchange ideas and come up with some possible solutions for this situation. 👍
