### ISSUE TITLE
Error saving draft on a resource that already has a draft

### ISSUE THREAD

**Issue by chrisdpeters** [liveeditor/draftsman#61]
As @andymcintosh pointed out in #59, there may be an issue with saving a draft on a resource that already has a draft when there is no `object_changes` column in the `drafts` table.

**Comment by andymcintosh** [comment]
Thanks Chris, I considered making a new issue but wanted to collect a little more information. I have isolated the behavior in a simple (Dockerized) Rails app if that helps at all. I can find no discernible problems with using the '--with-changes' flag in my case, so I'm able to move forward. Just wanted to share what I learned.

**Comment by chrisdpeters** [comment]
@andymcintosh For sure! I'm glad you commented on the other issue because it gives me a case to play around with for that issue.

**Comment by jmfederico** [comment]
For some reason track_object_changes_for_draft? is always returning true, even when the column does not exist.

**Comment by jmfederico** [comment]
The problem is in line 400 of model.rb
````ruby
            if self.draft? && self.draft.changeset.key?(attr)
````

Changing it to:
````ruby
if self.draft? && self.draft.changeset && self.draft.changeset.key?(attr)
```
Fixes it for me, but not sure if it breaks something else.
