### ISSUE TITLE
Sinatra extension should not use Sinatra base namespace

### ISSUE THREAD

**Issue by batter** [liveeditor/draftsman#9]
Hi, I'm the maintainer of [PaperTrail](https://github.com/airblade/paper_trail). We just had an issue filed against the PaperTrail repo, airblade/paper_trail#477, which was being caused by this gem.

I see that your gem here was cloned off of the PaperTrail source at one point.  I wanted to advise you to modify your `Sinatra` extension so that it is not namespaced under the `Sinatra` module, as this can cause conflicts when other libraries look to see if `Sinatra` is defined.  For more details see airblade/paper_trail#277.

I would recommend simply adjusting [your `Sinatra` module](https://github.com/liveeditor/draftsman/blob/0.3.1/lib/draftsman/frameworks/sinatra.rb) so that it is namespaced under the `Draftsman` module.  You can [mimick what we are doing on `PaperTrail`](https://github.com/airblade/paper_trail/blob/v3.0.6/lib/paper_trail/frameworks/sinatra.rb) if that helps you.

**Comment by chrisdpeters** [comment]
Thank you for the pointers; it makes things really easy for me to fix. I have not had an opportunity to try this gem with Sinatra yet, so your advice is invaluable!

**Comment by chrisdpeters** [comment]
@rikkipitt Can you verify if this fixes the issue that you were encountering when mixing this with PaperTrail?

**Comment by rikkipitt** [comment]
Cheers @chrisdpeters, I'll take a look as soon as I get chance and let you know! Thanks for sorting this out!

Rikki
